### ISSUE TITLE
missing image in patching/changing-the-patch.md

### ISSUE THREAD

**Issue by icke-siegen** [AvolitesLtd/TitanManual#107]
In patching/changing-the-patch.md, close to 'Range Mapping', an image is missing. Probably something like this: 
![mapping](https://user-images.githubusercontent.com/70575174/92115100-3aa54680-edf2-11ea-8624-c8b35b9e7f7d.png)

**Comment by garethnunns** [comment]
I believe this was fixed in 1789d39b29dd00df42d17824ebcf106af2935a76 (now merged) but this image does look more useful, feel free to replace with something similar to this

**Comment by icke-siegen** [comment]
This is what I mean:
![image](https://user-images.githubusercontent.com/70575174/92160006-a1485580-ee2e-11ea-8a40-bc72935b7059.png)

Currently it links to the same image as above /Exchange-Mapping.png). I do not know how I could add a new image myself :-(

**Comment by garethnunns** [comment]
I think an image similar to yours would show it more clearly under the **Range Mapping** heading.

### To add a new image
1. Add the image to [`./website/static/docs/images`](https://github.com/AvolitesLtd/TitanManual/tree/master/website/static/docs/images)
2. Name it something SEO friendly like the other images in the folder, *e.g. `Exchange-Mapping-Range-Mapping.png`*
3. Add it to the MarkDown file with some alt text, *e.g. `![Exchange Mapping with range mapping](/docs/images/Exchange-Mapping-Range-Mapping.png)`*

Or I'm happy to make the update if you drop the image here 👍

**Comment by icke-siegen** [comment]
I don't have permissions to add a file (would need push access). Thus I simply put it here.

![Exchange-Mapping-Range-Mapping](https://user-images.githubusercontent.com/70575174/92206015-1a739700-ee87-11ea-9d81-7ff9594ab23b.png)

Re. latest master: so far I am doing everything online. Isn't this automatically working with the latest master?

**Comment by garethnunns** [comment]
I'm happy to do this if you'd like or if you want to make larger changes in future, I would recommend:
1. [Fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks) this repo
2. Clone your forked repo to your local computer, using [GitHub Desktop](https://desktop.github.com/) (or git command line)
3. Create a [branch](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-branches) for your feature/correction, branching from the [upstream master](https://www.atlassian.com/git/tutorials/git-forks-and-upstreams) ([this repo's master](https://github.com/AvolitesLtd/TitanManual))
4. Make all your changes locally on your computer, then [commit](https://docs.github.com/en/github/committing-changes-to-your-project/about-commits) and push it to your fork
5. [Create a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) into this repo's master
