### ISSUE TITLE
Redundant chapter on personalities

### ISSUE THREAD

**Issue by icke-siegen** [AvolitesLtd/TitanManual#120]
The chapter on personalities exists twice, with same contents but different formatting: https://manual.avolites.com/docs/next/patching/fixture-personalities/ and https://manual.avolites.com/docs/next/fixture-personalities/

I'd suggest to remove one (possibly the one in the patch section), and replace it with a link to the main chapter.

**Comment by garethnunns** [comment]
Or do you think we should remove the chapter to make it less to scroll through on the console? Having it in the patch chapter feels a good place

**Comment by congoblue** [comment]
I would say remove this section from the patching chapter and leave as a separate chapter. There is already a link in the "patching fixtures" section which takes you to the separate chapter.

**Comment by icke-siegen** [comment]
> Or do you think we should remove the chapter to make it less to scroll through on the console? Having it in the patch chapter feels a good place

Nah, I don't think so. While patching is an everyday task, personalities is much more special, and only interesting for a very small usergroup.
