### ISSUE TITLE
PC suite Specs 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#135]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/titan-basics/titan-simulator/

**Old Text (if applicable):**
From v7, Windows XP and Vista are no longer supported by Titan software. Your PC must be running a 64 bit version of Windows 7, Windows 8.1 or Windows 10.

**New Text:**
From v7, Windows XP and Vista are no longer supported by Titan software. Your PC must be running a 64 bit version of Windows 7, Windows 8.1 or Windows 10. V13 + Require Windows 10 64bit bit only 

**Why it should be changed:**
It's my understanding that v13+ require Windows 10 64Bit only.

**Other Information:**
I suspect this may also be in other places in the manual

**Comment by KadeBehm** [comment]
It is also on this page https://manual.avolites.com/docs/next/titan-basics/

**Comment by KadeBehm** [comment]
I'd also like to suggest that the PC suite hardware specs be listed in the manual , esp since it can be changed easy and gives us in support a place to direct people .

**Comment by congoblue** [comment]
Can we confirm that it is correct that W10 64 bit is required for Titan v13+ ?
Also confirm the recommended hardware specs for a PC to run Titan v13+?

**Comment by KadeBehm** [comment]
These are what UK support is sending to users 

https://www.avolites.com/titan-pc-system-requirements/?fbclid=IwAR1NkE3BerAm_9b-Xe2kbEGzaPj-Fe9m_HBa_z_5ULVP57kerQtHv9n-Mbg <https://www.avolites.com/titan-pc-system-requirements/?fbclid=IwAR1NkE3BerAm_9b-Xe2kbEGzaPj-Fe9m_HBa_z_5ULVP57kerQtHv9n-Mbg>


V13 windows 64 bit I was told required by Fraser and if you try to  install it on a 32bit install  it errors out ( found this with multiple customers ) 

Kade Behm
(303)944-4504
clublights@mac.com

**Comment by congoblue** [comment]
OK thanks will update relevant sections.

**Comment by KadeBehm** [comment]
Should I add new places I find the same thing here to this or a new issue thread ?  https://manual.avolites.com/docs/about-the-consoles/t1-and-t2/

"T1 and T2 are USB dongles which plug into a PC or laptop (Windows 7 or above, 64 bit). Both dongles include an AvoKey."  should be Windows 10

**Comment by KadeBehm** [comment]
Also here 
https://manual.avolites.com/docs/titan-basics/#connecting-up-titan-mobile-and-t1t2

**Comment by garethnunns** [comment]
I'd be a fan of specing the requirements once and referring to that in other places, we could have a PC Suite section under the About The Consoles section? As with a key you can do one universe so it is a console in a sense

**Comment by congoblue** [comment]
Yes it is a good idea to have it in one place to make updating easier.

I will create a reference section which the other places refer to. It applies to Titan Mobile as well as T1/T2/PC Suite though, so I don't think putting it in a PC Suite section would be the best place. Possibly 
https://manual.avolites.com/docs/titan-basics/#connecting-up-titan-mobile-and-t1t2
would be the best place for it

**Comment by KadeBehm** [comment]
https://manual.avolites.com/docs/next/titan-basics/titan-simulator/ 

another spot for it .

**Comment by congoblue** [comment]
I think I have got all these now in #145
