### ISSUE TITLE
Fire/Dont Fire Nested Palettes 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#149]
**Link to the page in the manual:**
https://manual.avolites.com/docs/palettes/creating-palettes/#nested-palettes

**Old Text (if applicable):**
When palettes are used in cues, you can disable the nested palettes using the playback option Fire/Don't Fire Nested Palettes. If set to Don't Fire, the nested palettes are treated as the fixed values they held at the time the cue was recorded and won't change if the nested palette is updated

**New Text:**
I don't have a good one for this yet

**Why it should be changed:**
The way this is presented I always though this option as in playback options for playback itself not in the options for the palette. I understand how it is supposed to work now after talking with pete in the beta forum but this wording needs some love. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
You are right, this text is confusing, it is not helped by the "Options" button previously being called "Playback Options", and the reference to cues is wrong. 
How about explaining it like this:

If you've created a new palette using nested palettes, you can switch the palette to be non-nested (to use the values which were set at the time it was recorded). This can be useful if a palette was recorded as nested, but then you need to break the link to the source palettes so you can change them without changing the new palette. To find this setting, press /[Options/] then the handle of the palette, in the /[Palette/] tab switch off the option [/Fire Nested Palettes/]. You can reinstate the link by switching the option on again.

**Comment by KadeBehm** [comment]
That's much more solid a big thumbs up from me !
