### ISSUE TITLE
Mobile Wing correction 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#156]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/about-the-consoles/fader-wings/

**Old Text (if applicable):**
It is designed to fit next to the Titan Mobile panel, but it can also be used with the Tiger Touch, Quartz, Arena and Sapphire Touch consoles, and the Titan Two dongle.

**New Text:**
It is designed to fit next to the Titan Mobile panel, but it can also be used with the Tiger Touch, Quartz, Arena and Sapphire Touch consoles, and the T2 dongle.

**Why it should be changed:**
I think this is the only place it uses titan two  And I don't think it's called that anywhere in sales, website etc , 

**Other Information:**
I know sales / marketing has in the past not wanted us to use the word dongle with the t1 and t2 , not sure if we want to change anything on this

**Comment by congoblue** [comment]
Fixed in #161
