### ISSUE TITLE
TItan Net Sessions 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#157]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/titan-basics/multi-user-operation/

**Old Text (if applicable):**
If multiple Titan consoles are connected in the same network you can choose to connect them as multi-user, backup, or both. This is also how you connect TitanNet processors to expand DMX outputs.

**Old Text (additional ):**
Consoles must be running Titan v8 or above to join a multi-user or backup session with another Titan v8 console.

**New Text:**
If multiple Titan consoles are connected in the same network you can choose to connect them as multi-user, backup, or both. .
**New Text( additional):**
NONE remove it 

**Why it should be changed:**
tho TNP's are using "TitanNet "  they don't use the interface being talked about here, Making it slightly confusing , 

as for the v8/additional  just remove as software versions must match to use multi user, 

**Other Information:**
Hope to not drive you crazy but I'm reading thru the manual and looking for issues like this.

**Comment by congoblue** [comment]
Kade, keep them coming, it will be good to fix all of these things, some have changed with later versions but not been updated.

For versions I think it would be worth saying "Consoles must be running the same version of Titan to join a multi-user or backup session".

**Comment by KadeBehm** [comment]
Agreed that works too I think its said a few times above it but making it extra clear is good,
