### ISSUE TITLE
Clearing the console 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#158]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/titan-basics/clearing-the-console/

**Old Text (if applicable):**
When you start a new show on Titan it is usually a good idea to clear the console. All programming and patching is deleted, but user options are not changed.

**New Text:**
Not sure 

**Why it should be changed:**
Some user settings are lost and some are kept Example the very first two user options( chase snap and cue list snap)  revert to default on a new show but like external display does not . 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
should probably say "user options are returned to default settings"?

**Comment by KadeBehm** [comment]
Yeah I think that is more true  and a user doesn't expect things to be sticking that don't.  The display settings being in user settings is a new for v14 thing so it throws a slight curve to it . I cant think of much more that does stay, off hand I could go thru every setting but I think thats a bit over kill .
