### ISSUE TITLE
Patching section Error .. sorta 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#159]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/patching/changing-the-patch/

**Old Text (if applicable):**
at the bottom: 
The new personality is loaded from the Titan/Personalities folder.

**New Text:**
Not Sure 

**Why it should be changed:**
This text almost doesn't fit the section its attached to 
if the update is form a personality updater it is in the D:/titandata/fixturelibrary ( hidden folder on the consoles ) or the C:/programfiles(x86)/Avolites/Titan/fixturelibrary on the PC suite Or the D:/personalities if user installed on console and ~/documents/titan/personalities on the PC suite 

Really I'd just remove it.  all above is too much info for the user but the original line is not correct , 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I will remove it, this has changed many times with the different Titan versions and different Windows versions.
