### ISSUE TITLE
Syntax of sub fixtures 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#167]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/controlling-fixtures/using-the-select-buttons-and-wheels/#fixtures-with-multiple-cellssub-fixtures

**Old Text (if applicable):**
You can also use the numeric keypad to quickly select cells. The syntax is as follows: (THRO is called Through on some consoles)

. all sub-fixtures of selection

n. all sub-fixtures of fixture n

. THRO .j sub-fixtures 1j of all selected fixtures

n. THRO all sub-fixtures of fixture nlast consecutive of type

n THRO .j shorthand for above

n. THRO i sub-fixtures 1i of fixture n

.m sub-fixture m of all selected fixtures

n. THRO i.j sub-fixtures 1j of fixtures ni

.m THRO sub-fixtures mlast of all selected fixtures

n.m sub-fixture m of fixture n

.m THRO .j sub-fixtures mj of all selected fixtures

n.m THRO sub-fixtures mlast of fixture n

.m THRO j shorthand for above

n.m THRO i sub-fixtures mi of fixture n

n THRO i. all sub-fixtures of fixtures ni

n.m THRO i. sub-fixture mlast of fixtures ni

n THRO i.j sub-fixture j of fixtures ni

n.m THRO i.j sub-fixtures mj of fixtures ni

n THRO .j sub-fixture 1j of fixture n

n.m THRO .j sub-fixtures mj of fixture n

Fixture cell selection can be saved as a group, this provides a quick way to select cells / sub-fixtures without having to use the Attribute Editor or Unfold.

**New Text:**
Not sure 

**Why it should be changed:**
This section is messy  and I'm not sure where all the J's are coming from . and seems to be missing spaces  or colons 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
This has already been fixed in #125-#126 but has not made it into the online version yet. It got messed up in the conversion to markdown

**Comment by garethnunns** [comment]
We could do a release @Farrser?
