### ISSUE TITLE
Channel grid 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#171]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/controlling-fixtures/viewing-and-editing-fixture-values/

**Old Text (if applicable):**
It can sometimes be useful to display and edit exactly what each fixture is doing. The Channel Grid window allows you do to that. Display it by pressing VIEW/OPEN then Open workspace window then Channel Grid.

**New Text:**
It can sometimes be useful to display and edit exactly what each fixture is doing. The Channel Grid window allows you do to that. Display it by pressing Open workspace window then Channel Grid.

**Why it should be changed:**
No need ot press open/view first  seems redundant esp in the face of v14 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I will edit this - we are now using "Double press VIEW/OPEN button to show the Workspace Windows buttons" as the standard way of opening a workspace window as this works at any time, rather than the Open Workspace Window softkey which requires you to be in the top level menu.

**Comment by congoblue** [comment]
Actually this is already fixed as above
