### ISSUE TITLE
Quick Record 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#173]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/palettes/creating-palettes/#quick-record

**Old Text (if applicable):**
image of the workspaces record/recall space

**New Text:**
The image should be changed to a palette window and not the workspaces record/recall space image . 

**Why it should be changed:**
Image can lead to confusion . 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I agree, unfortunately there seems to have been a process of trying to re-use images from different parts of the manual which has resulted in some incorrect or unsuitable images being shown. I will put this one back in.
