### ISSUE TITLE
Auto Legends

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#174]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/palettes/creating-palettes/#storing-a-palette

**Old Text (if applicable):**
The console will automatically create a legend for your palette (unless the User Setting Auto Legend is set to Off). For colour palettes a coloured icon is used to show the selected colour. If the palette contains fixtures set to different colours, a coloured bar will be shown for each. For CITP (media server) palettes, the media thumbnail will be used. For other attributes the last adjusted function value will be used for the legend, except for pan and tilt which will use a default legend.

**New Text:**
The console will automatically create a legend for your palette (unless the User Setting Auto Legend is set to Off). For colour palettes a coloured icon is used to show the selected colour. If the palette contains fixtures set to different colours, a coloured bar will be shown for each. Gobo's will show the gobo image ( if available in the personality). For CITP (media server) palettes, the media thumbnail will be used. For other attributes the last adjusted function value will be used for the legend, except for pan and tilt which will use a default legend.

**Why it should be changed:**
This was added in V11. may want add the blue info box about updating personalities. and may wish to add an image of the gobo icon legends next to the color ones. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
Fixed by #180
