### ISSUE TITLE
Context Menu 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#175]
**Link to the page in the manual:**
NA as it is thru out the manual 

**Old Text (if applicable):**
NA

**New Text:**
Link to the Context menu section 

**Why it should be changed:**
The Context Menu is one users seem to be hard pressed to get .  I think evey time it is mentioned it should be a link to the manual section on it. or at the very least that when I search for "context menu"  it is the very first result. right now it doesn't even come up as a result. 

**Other Information:**
I know it seems nit picky but I have to explain where the context menu is almost every time I tell a user to press a button inside of it .

**Comment by congoblue** [comment]
Do you mean, where it is physically positioned on the screen?
