### ISSUE TITLE
Shape Gen

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#178]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/effects/shape-generator/

**Old Text (if applicable):**
N/A

**New Text:**
In one of the blue info boxes : "After adjusting things such as offset and phase Restarting  a shape can be useful to see how it will look when fired fresh from a cue or to see how your cycles look from a start .you can restart shape for the edit menu while in the shape generator menu " 

**Why it should be changed:**
Too many don't know this exists, and try to adjust the offset or phase then after recording and playing back do not get the same look . 

**Other Information:**
what exactly should I call those blue info boxes ?

**Comment by KadeBehm** [comment]
This is .. sorta .... here .. but should be added to the building a shape section also for the reasons I Said above  

https://manual.avolites.com/docs/next/effects/editing-shapes-and-effects/#resynchronise-shapes

**Comment by congoblue** [comment]
I am just calling them "info boxes".
