### ISSUE TITLE
Shapes in cues 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#179]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/effects/shape-generator/#using-shapes-in-cues

**Old Text (if applicable):**
You can also adjust parameters of the shape at playback time using the Select Shape menu, which is on the Edit menu of the Shape Generator menu.

**New Text:**
You can also adjust parameters of the shape at playback time using the Select Shape menu, which is on the Edit menu of the Shape Generator menu. this can also be done by pressing the Cue/Connect key  then the Shapes Key and sleeting which shape ( if more then one is running ) from the softkeys

**Why it should be changed:**
This way is faster and more elegant . 

**Other Information:**
Any other information

**Comment by KadeBehm** [comment]
I see this is in the editing a live running shape section ... probably could ignored here.  Sorry ,

**Comment by congoblue** [comment]
Have added a link to the other section
