### ISSUE TITLE
Contextual buttons

### ISSUE THREAD

**Issue by garethnunns** [AvolitesLtd/TitanManual#182]
Is it worth doing a separate formatting for buttons in windows, we often refer to them as **+**, **X**, etc.

Suggestion we could use `\(+\)` or just use the same formatting as softkeys?

**Comment by congoblue** [comment]
I think it would be fine to just use the same formatting as the menu softkeys. 
They are all touch screen buttons.

**Comment by garethnunns** [comment]
We can potentially add images into the text - it needs to work well with the PDF too. 

It would be easy to match the styling of the onscreen buttons using the text based method which might make it clearer for users.

**Comment by garethnunns** [comment]
> The difficulty is for graphical buttons, e.g. "cog" button or the group delete buttons on the DMX outputs screen which are not really "X". It would be nice to be able to put a small bitmap inline with the text, I don't know if that is possible.

I have now implemented this 👍
