### ISSUE TITLE
Playing back a cue 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#186]
**Link to the page in the manual:**
https://manual.avolites.com/docs/cues/using-a-cue/#playing-back-a-cue

**Old Text (if applicable):**
To assign Preload, hold AVO Shift and press Edit Key Profile, then press the button you want to assign (also see Key Profiles). Note that this will assign the function to all buttons of the same type.

**New Text:**
To assign Preload, hold AVO and press Edit Key Profile, then press the button you want to assign (also see Key Profiles). Note that this will assign the function to all buttons of the same type.

**Why it should be changed:**
having " shift" after the avo key here makes it seem like I need to press a shift key also.

**Other Information:**
Any other information

**Comment by congoblue** [comment]
It was called "Avo Shift" button a long time ago. I will remove this

**Comment by congoblue** [comment]
Help! The section "using-a-cue.md" which this section is in, has disappeared from the master branch - does anyone know why?

**Comment by garethnunns** [comment]
It's now called cue-playback.md, changed in #115 to resolve #111, making it more consistent

**Comment by congoblue** [comment]
Ah.... also changed other occurrences of this through the manual

**Comment by KadeBehm** [comment]
https://manual.avolites.com/docs/next/running-the-show/playback-controls/#flash-and-swop-buttons Probably already fixed but adding here just in case

**Comment by KadeBehm** [comment]
Same https://manual.avolites.com/docs/next/running-the-show/playback-controls/#busking-with-palettes
