### ISSUE TITLE
Handle button naming

### ISSUE THREAD

**Issue by garethnunns** [AvolitesLtd/TitanManual#189]
Confirm the name for the buttons above the faders for disambiguation between:
- "blue fader button"
- "blue button"
- "Swop"
- "swop"
- "select"
- "Select"
- "handle button"
- "Flash"
- "fader select"

We could also do some styling if this would help clarity

**Comment by congoblue** [comment]
It would be helpful if someone who had access to all the consoles could confirm how the buttons are actually labelled on each console model.

**Comment by KadeBehm** [comment]
I have 4 of the 5 current consoles here they are not labeled at all . the 5th ( the TT2 ) is not labeled either as far as I know,

**Comment by KadeBehm** [comment]
And searching some images real quick both current wings ( Mobile and TT ) are not labeled and the TT2 is not labeled in images I looked at too .

**Comment by KadeBehm** [comment]
just had gordon confirm those all are unlabeled also since he had a tt and tt wing in his class I pulled out my mobile wing same .

**Comment by garethnunns** [comment]
In the Titan Go they were labelled "Swop" & "Flash" in the UI and the referred to as "Blue Key" & "Grey Key" in [key profiles](https://youtu.be/CxHQV4sP_sA).

**Comment by KadeBehm** [comment]
They were  but are now in V14 will change with their assignment in key profiles and will be blank on an unprogrammed fader.

**Comment by garethnunns** [comment]
What are they referred to as in the key profile section in v14?

**Comment by KadeBehm** [comment]
Virtual Black ( if not using a sapphire) 
Blue Key
Grey Key
Touch/ Executor Key 

Getting Executor added to the touch key has been something I've been begging for for years,.

**Comment by KadeBehm** [comment]
if you area on a sapphire it just says black key .

**Comment by KadeBehm** [comment]
I think in terms of the faders we can refer to them as their color ,  Executor's can be grey or blue depending on console and vintage. I think  just calling them Executors is the safe bet,

**Comment by garethnunns** [comment]
In the manual should they match that? e.g. "press the Blue Key for the fader"

**Comment by congoblue** [comment]
There are reasons I can't go into now why I don't think we should do this. I think this issue should be left as it is for now.

**Comment by congoblue** [comment]
This has now been standardised as "the **Select** button".
