### ISSUE TITLE
Info box Playing back a chase 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#190]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/chases/chase-playback/#playing-back-a-chase

**Old Text (if applicable):**
The HTP (intensity) channels in the chase will be controlled by the fader; if fade times are programmed, the fade will stop at the fader level. The other channels (LTP) will be set as soon as the fader moves above zero according to the fade times programmed in the chase. You can set the point at which the LTP channels activate from the User settings menu.

**New Text:**
Not Sure ?

**Why it should be changed:**
Where is this setting ? I seem to recall we could change where a fader started from in classic but not in Titan any . 
Or I'm confused by the text: "You can set the point at which the LTP channels activate from the User settings menu." 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I think this is leftover from Classic version. I don't believe you can set this in Titan. I'll remove it
