### ISSUE TITLE
Fixture overlap 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#197]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/cue-lists/cue-list-timing/#fixture-overlap

**Old Text (if applicable):**
To change the fixture order when using overlap, press Set Fixture Order. Normally this is the order in which you selected the fixtures when you programmed the cue. The Fixture window shows the fixture order in large green numbers. Reorder the fixtures by pressing Step Number then type the start number on the numeric keys, then press the fixture Select buttons in the order you want them.

**New Text:**
To change the fixture order when using overlap, press Set Fixture Order. Normally this is the order in which you selected the fixtures when you programmed the cue( or from the Fixture order saved to the group used) . The Fixture window shows the fixture order in large green numbers. Reorder the fixtures by pressing Step Number then type the start number on the numeric keys, then press the fixture Select buttons in the order you want them.

**Why it should be changed:**
This is in a few places but I t's now bothered me enough to add , I think it matters they understand that the groups can have fixate order and it is used with recording a playback. My text could be improved. 

**Other Information:**
Should I go back and find other places of this ?

**Comment by garethnunns** [comment]
#138 made it so it's only mentioned in one place, so this text only needs updating in cue timing I believe.
