### ISSUE TITLE
Theatre Programming 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#199]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/cue-lists/theatre-programming/

**Old Text (if applicable):**
too much to list 
**New Text:**
NA 

**Why it should be changed:**
Shouldn't this have all the same key/button styling as the rest of the manual ? seems odd to not have the same thing here 

**Other Information:**
Any other information

**Comment by garethnunns** [comment]
This has been fixed in #155 but this hasn't been released to the website, when @Farrser is in the office next week we'll do a release. You can see when the website was last updated by viewing the versions page: https://manual.avolites.com/versions/

**Comment by KadeBehm** [comment]
Fair Enough .
