### ISSUE TITLE
External Display

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#225]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/system-settings/external-displays/

**Old Text (if applicable):**
An external display is disabled by default and will show a 'disabled' message. To enable, switch to System mode and select Display Setup then press External Display Disconnected. The option will change to External Display Connected and the display will be enabled.

**New Text:**
An external display is disabled by default and will show a 'disabled' message. To enable, enter the System menu and select Display Setup then press External Display Disconnected. The option will change to External Display Connected and the display will be enabled.

**Why it should be changed:**
We don't really switch to the system mode so much as enter the system menu in current consoles. 

**Other Information:**
Would you prefer my consolidating these like this or each one a new issue ?

**Comment by KadeBehm** [comment]
Also here , under the first video 
https://manual.avolites.com/docs/next/system-settings/key-profiles/

To create or edit a profile, switch to System mode then select Key Profiles. You can then use the Manage Profiles menu to View, Edit, Add, Delete or Rename profiles.

**Comment by KadeBehm** [comment]
Here also 
https://manual.avolites.com/docs/next/system-settings/dmx-output-mapping/#configuring-dmx-outputs
Switch the console to System mode and select DMX Settings.

**Comment by KadeBehm** [comment]
https://manual.avolites.com/docs/next/system-settings/dmx-output-mapping/#module-properties
(switch to System mode and select DMX Settings)

**Comment by congoblue** [comment]
"switch to system mode" sounds OK to me, it does not mean that there is a keyswitch to turn because "switch" can just mean "change". It is probably one of those (many) strange English language things but for example on the TV you would say "switch over to another channel" but you're just pressing a button.

I am not sure about "enter system mode" because you are actually changing the operating mode of the console, lots of things are different in system mode, and for me "switch to system mode" makes it clearer that you are putting the console into a completely different mode where some functions no longer operate.

**Comment by KadeBehm** [comment]
but when you press the system key on titan go or avo disk on a console the bar between the keypad/context menu says " system menu"  All I think a lot of what used to be not able to do in the past is not true anymore , I can still fire playbacks use flash and swop keys fire palettes. I also found other places where it is referred to as system menu . so I guess we need to decide which is proper and change it to be consistent ,  in testing so far al I cant do when in the system menu is change workspaces , and use the program menu softkeys . ( since they are replaced with the system menu ones)

**Comment by Farrser** [comment]
Yeah there isn't really a system mode any more, it's just a menu. The workspaces not working is probably a bug in all honesty there is no reason that shouldn't work

**Comment by KadeBehm** [comment]
They "disaapear" off the screen when in the system menu ,  probably harkens back to it being a true mode and legacy consoles.

**Comment by congoblue** [comment]
OK I'll swap it. I'm just an old fashioned user who still thinks of it as a special mode.

**Comment by KadeBehm** [comment]
Another place:
https://manual.avolites.com/docs/next/networking/controlling-fixtures-over-a-network/#setting-the-consoles-ip-address

1. Switch to System mode and press Network Settings

**Comment by KadeBehm** [comment]
https://manual.avolites.com/docs/next/networking/using-active-fixtures/#example-citp-setup 

Just listing as I see em !

**Comment by KadeBehm** [comment]
https://manual.avolites.com/docs/next/titan-basics/#other-connections 

You can set the brightness of the desk lamps from System mode.

**Comment by KadeBehm** [comment]
https://manual.avolites.com/docs/next/patching/
