### ISSUE TITLE
DMX output Module Properties 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#232]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/system-settings/dmx-output-mapping/#module-properties

**Old Text (if applicable):**
NA

**New Text:**
DMX Output Properties
**image of settings**
DMX output: Allows you to temporarily disable the output
Merge Priority: A value between 0 and 200 where higher numbers have priority. Allows a node to chose which console to follow where multiple consoles are transmitting.
Break Length: This is the time Between DMX packets. By default this is 968us, In circumstances where a fixture can be seen with an occasional glitch try increasing this number. Some dimmers will require this to be 4000us in order to work smoothly
Mark After Break Length:Usually this will not need to be adjusted.
Extra Stop Bit: Enabling this adds an Extra Stop Bit to each byte. This option can sometimes solve issues where fixtures can be seen regularly glitching. 

**Why it should be changed:**
No reason not to ? 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I will add this in but is the software description of "Break Length" actually correct?
"Break" in DMX terminology is the "Low" signal at the start of each packet and it is normally about 100usec (min 88usec). 968 is enormous for a DMX break.
It sounds like this is actually setting the idle time between DMX frames rather than the break time.

**Comment by KadeBehm** [comment]
If I hook up my DMX tester it calls it break length also and that what changes when I change that value.  And I think the description is right when I read specs

**Comment by p--b** [comment]
@owaits can probably clarify exactly what this setting is.
