### ISSUE TITLE
Networking 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#234]
**Describe the bug**
Page comes up blank 

**To Reproduce**
1. Go to 'https://manual.avolites.com/docs/next/networking/'

or click on the " Networking the Console" link in the sidebar. 

**Expected behavior**
not to be a blank page LOL 

**Screenshots**
dont think this is needed 

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser safari
 - Version 14.0

**Additional context**

**Comment by KadeBehm** [comment]
Now this is interesting if I click the link above it works  but if I use the links in the manual it comes up blank .  odd one that

**Comment by KadeBehm** [comment]
And now the links work  I dunno if this was fixed or was a server hiccup or if it's just one of those days for me ,

**Comment by Farrser** [comment]
Not able to reproduce
