### ISSUE TITLE
Networking - Switches

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#235]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/networking/

**Old Text (if applicable):**
Lighting networks need to transfer of large amounts of data. For best reliability you should use network wiring which is dedicated to the lighting system and physically isolated from other networks, and uses simple hubs rather than intelligent switches.
Connecting to an existing network with other network traffic is possible but can lead to problems both with the lighting equipment and with other IT equipment on the network. Intelligent Ethernet switches may drop or block lighting data. If you need to do this please read about the IP addresses you should use in the IP addressing guide.

**New Text:**
Lighting networks need to transfer of large amounts of data. For best reliability you should use network wiring which is dedicated to the lighting system and physically isolated from other networks, and uses unmanaged gigabit switches rather than intelligent managed switches.
Connecting to an existing network with other network traffic is possible but can lead to problems both with the lighting equipment and with other IT equipment on the network. Intelligent managed Ethernet switches may drop or block lighting data. If you need to do this please read about the IP addresses you should use in the IP addressing guide.

**Why it should be changed:**
No one uses hubs anymore and managed /unmanaged is more correct ,. 

**Other Information:**
Any other information

**Comment by p--b** [comment]
I'd rather we were a bit more cautious with our guidance RE managed/unmanaged; for most users unmanaged dumb switches are going to be the most sensible route, but there will be situations in which managed switches are sensible and useful. If we're changing this wording I'd rather we changed it to something along these lines.

**Comment by KadeBehm** [comment]
Fair I just wanna get away from using hubs.

**Comment by congoblue** [comment]
I have heard of stories where managed switches block Art-Net because it looks like a Denial Of Service attack due to the repeating identical data. Never seen it myself though. Is this true and do we need to warn about it.

**Comment by KadeBehm** [comment]
This is true , I Think maybe I need to clarify my managed switches to what I meant. ,  a "Properly set up managed switch" the TNS and the TNS in an Arena are managed switches  but they are set up correctly. nothing wrong with a managed switch you just need to set it up correctly .

**Comment by p--b** [comment]
@congoblue it certainly happens (we see it in the office occasionally...) - but as the number of "entertainment specific" managed switches (from a variety of different manufacturers, including ourselves!) increases we'd be quite keen for users to use this kind of switch and don't want to put them off unnecessarily.

**Comment by KadeBehm** [comment]
Maybe some language a long the lines of “ either an unmanaged switch or a entertainment class switch” ?

**Comment by p--b** [comment]
"an unmanaged switch, an entertainment-class managed switch, or an IP network set up by an entertainment networking professional" probably covers the use cases we'd _actually_ recommend people use.

**Comment by KadeBehm** [comment]
I think I like that .

**Comment by congoblue** [comment]
I have updated this section in PR #241 . The Art-Net examples were very out of date so I have updated the whole section using a rackmount DMX node and a Powercube as the example devices.

It would be great to include a picture of the DMX Settings screen for this setup but I don't have either a Powercube or a DMX node here...
