### ISSUE TITLE
Art net diagrams 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#236]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/networking/controlling-fixtures-over-a-network/#a-simple-art-net-system

**Old Text (if applicable):**
All the network diagrams with "Network hub" 

**New Text:**
Should be be Netwiork Switch 

**Why it should be changed:**
Not sure if these can be changed but I thin they should be. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
Have updated whole section in #241 using more up to date equipment
