### ISSUE TITLE
Cross over cables 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#237]
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/networking/controlling-fixtures-over-a-network/#setting-up-an-art-net-system

**Old Text (if applicable):**
For this example, it is assumed that you will connect the console to an Art-Net DMX output box (such as an Artistic License Net-Lynx) via a network hub.

Art Net Explanation Simple System 
Using standard RJ45 Ethernet cables, attach the devices together.

If you are using a hub/switch as shown above, use straight-through patch cables. If you are directly connecting the console to another Ethernet device you need to use crossover cable

**New Text:**
For this example, it is assumed that you will connect the console to an Art-Net DMX output box (such as an Artistic License Net-Lynx) via a network switch.

Using standard RJ45 Ethernet cables, attach the devices together.
.
**Why it should be changed:**
Never hubs always switches 

And a Switch should always be used , straight thru leads to problems much too often . even tho most nic's auto cross over I've seen many artnet system fixed magically by adding a switch. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
I have removed this section as really it just repeats the previous section and the individual net-lynx nodes in the example are obsolete.
