### ISSUE TITLE
Images are not versioned

### ISSUE THREAD

**Issue by congoblue** [AvolitesLtd/TitanManual#242]
The images in the manual are not versioned. This means that if you change/update an image for a new software version, the image will also incorrectly change in previous versions.

We can work round this by always creating new images when features change but this is complicated as images are sometimes used in more than one place in the manual. It would be better to just be able to update the image for the new version and have the old image remain for the older versions.

**Comment by garethnunns** [comment]
Unfortunately this is how versioning in Docusaurus currently works: https://github.com/facebook/docusaurus/issues/1257

If an image is being changed then it could be prepended with the version number, e.g. `v14-Wheels.png`, or a similar naming convention.

**Comment by congoblue** [comment]
OK we will do it like that. 

It is important that when approving changes we are on the lookout for images being overwritten as this may invalidate earlier versions of the manual - unless the image change is just an improvement to an existing image which will also be valid for earlier versions.
