### ISSUE TITLE
moving 'playback groups' to 'running the show'?

### ISSUE THREAD

**Issue by icke-siegen** [AvolitesLtd/TitanManual#251]
I'd like to suggest to move the chapter on playback groups (https://manual.avolites.com/docs/next/cues/playback-groups/) into the section 'running the show' (https://manual.avolites.com/docs/next/running-the-show/).

Playback groups is a feature to organise the console, and works for cues, chasers, and cue-lists. Hence I'd rather see this in the 'running the show' section.

In the long run we should also consider a little chapter on busking (as like as the theatre chapter) - I am envisioning busking with palettes, playback groups, key profiles, scene master and blind-to-live to be part of this.

**Comment by congoblue** [comment]
I think this is a good idea, and I agree that we could have a section on busking - some of the parts of the "Running the Show" chapter already cover this and could be gathered together.

I believe we are about to release the manual for v14 so I suggest that these changes are held until that is done, and we will put them in the next version. I would like to break up the "Controlling fixtures / Attribute editor" etc section too as that needs splitting into smaller sections.
