### ISSUE TITLE
Add icon graphics for timeline view window

### ISSUE THREAD

**Issue by congoblue** [AvolitesLtd/TitanManual#294]
It would be useful to be able to display the button icons in the Timeline View window using the curly bracket "softkey" notation, namely:

- Back to 0 ( |< )
- Play from start ( |> )
- Play and Pause
- Record
- Timeline linked and Timeline Unlinked
- Pointer Arrow
- Hand
- Lock/padlock icon
- Power on/off button icon
- Left/right arrow buttons

**Comment by congoblue** [comment]
Also, I think for the existing icon buttons you've created, it would be clearer to just have the symbol as it is displayed on screen, rather than the symbol and text - e.g. the "Link" button in the manual shows the chain link symbol and the word "Link", but the onscreen button just shows the link symbol with no text - I think this is confusing as users will look for the button as it is illustrated in the manual. So I would suggest removing the text from these buttons.

**Comment by garethnunns** [comment]
Yes we can add these, when I'm next free I'll find some suitable icons.

The thought with keeping the text was to aid copy & pasting the text, plus SEO and for those with accessibility issues. That being said, yes, this would be easily achievable.

**Comment by congoblue** [comment]
OK I see the reason for adding the text - I think accessibility could be done by describing it in the text the first time, i.e. Press the Cog button \{Cog\}. Or perhaps it could render automatically with the symbol in the grey box followed by the text in plain text, so that it doesn't appear the text is on the button?

**Comment by Farrser** [comment]
I can see the value in the text being there. Like you say maybe adjusting the styling so it doesn't look so much part of the button would be best. Really I think we should probably change this in Titan so that buttons with icons always have a text name too.

**Comment by Farrser** [comment]
@congoblue think these are all good now?

**Comment by congoblue** [comment]
Yes they all look good. Though still with the reservations about having the text shown within the grey box.
