### ISSUE TITLE
Add a section to the manual about cleaning the consoles

### ISSUE THREAD

**Issue by Farrser** [AvolitesLtd/TitanManual#297]
Quite a few people have asked about how to clean the consoles. Would be good if we could add something about this in the about the consoles section.

There are some existing resources we can use/reference:

https://www.avolites.com/support/titan-faqs#la-2405300-covid-19-cleaning-advice

https://www.youtube.com/watch?v=zfecVxfBihw

https://www.youtube.com/watch?v=RkCbBQ324fE

**Comment by congoblue** [comment]
As a maintenance task I would suggest this goes later in the manual possibly next to the "upgrading the software" section.

I'm not really sure about including those youtube links - 
the first one is very old ("the new white Pearl Expert") and shows using meths but the faq specifically says not to use anything with alcohol. And the second does not really address cleaning, just fader maintenance.

**Comment by Farrser** [comment]
> As a maintenance task I would suggest this goes later in the manual possibly next to the "upgrading the software" section.
> 
> I'm not really sure about including those youtube links -
> the first one is very old ("the new white Pearl Expert") and shows using meths but the faq specifically says not to use anything with alcohol. And the second does not really address cleaning, just fader maintenance.

Yeah, that probably makes sense.

I was more saying using these as sources for some sort of maintenance / cleaning section. I'm not sure about the meths situation, I've definitely cleaned consoles with meths before! It may be that we wouldn't recommend doing this as a daily cleaning method but it is okay if the console is very dirty. I will seek clarification.

**Comment by congoblue** [comment]
So have I, when someone has been over enthusiastic with a sharpie.
