### ISSUE TITLE
New cheat sheet section with shortcuts

### ISSUE THREAD

**Issue by marcheimendinger** [AvolitesLtd/TitanManual#319]
A new section named _Cheat Sheet_ or _Shortcuts_ would be very useful for every users, beginners or advanced, as a quick reference.

This section would include every shortcuts on the console that are not obvious and/or hard to remember.

I thought about this yesterday, after learning about the use of Through/And keys as left/right arrows to navigate in timecode fields between minutes, hours, etc. This shortcut doesn't seem to be anywhere in the manual by the way.

**Comment by Farrser** [comment]
Agreed Marc, I think there are a number of these things that aren't included in the manual.

Maybe the mini academy tips and tricks list would be a good start?

https://www.facebook.com/groups/Avolites/permalink/1484835818315314/

**Comment by congoblue** [comment]
Pretty much everything in that list is in fact in the manual in various places, but as usual the problem is how to find them.

How can we gather together all the tips like this so I can make a section on them?

I think the timecode field thing is different depending on the console ... we did put in about using left/right arrows to go between seconds/minutes/hourse but of course some consoles don't have the arrow buttons marked - which consoles have Through/And as left/right arrows?

**Comment by Farrser** [comment]
I think the best way to gather them is probably to ask the training dept what they already have beyond that link I posted. Then maybe we can just add to it further as we go?

I believe the thru/and keys will always work as arrows even if the console has arrow keys

**Comment by congoblue** [comment]
OK sounds like a plan.

Are there keys for up/down arrows as well? I think some consoles have it printed on the panel next to the buttons, but some don't.

**Comment by p--b** [comment]
The D9 has all four arrow keys as dedicated keys. My understanding is that And/Thru aren't really arrow keys as far as the software is concerned, they are just overloaded to have left-subfield & right-subfield behaviour when in a timecode entry on all consoles. All consoles will respond to use of the keyboard arrow keys (if connected/present) in the same way as the console arrow keys on the D9.

**Comment by marcheimendinger** [comment]
Thank you all for your interest in my suggestion!

@Farrser Exactly, I forgot to mention the Academy tips and tricks but it made me think of what this new section could looks like.

**Comment by Farrser** [comment]
I think maybe this could go with https://manual.avolites.com/docs/en/next/titan-commands/ if we rename the section to "Quick Reference" for example.

I didn't find any more commands to start off with from other departments, so maybe we should just build up the list as we go.

**Comment by marcheimendinger** [comment]
This kind of document (sorry, from a rival!) can be very effective for beginners to print out and have close to the console while programming: https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737461763

**Comment by congoblue** [comment]
This section has now been added to the current master, please add suggestions if you know other shortcuts.
