### ISSUE TITLE
Add "Button Reference" section

### ISSUE THREAD

**Issue by congoblue** [AvolitesLtd/TitanManual#325]
Add a section which explains the function of each button and links to the relevant part of the manual.
Suggest this goes at the end of the "Quick Start" section at the beginning.

**Comment by p--b** [comment]
Suggest the `\<Button\>` syntax should auto-link to the appropriate page for that button in the reference.

**Comment by congoblue** [comment]
Would that be worthwhile - I was only thinking of a couple of lines explanation for each button, with a link to a more detailed part of the manual, so it isn't going to be pages and pages. We don't want to duplicate things. So really you'd just be linking back to the top of the alphabetic "Button Reference" section for every button - I would think people would know to click on the "Button reference" section if they find a button they don't understand.

**Comment by p--b** [comment]
So I was inspired by how our German colleagues do this: https://help2.malighting.com/Page/grandMA2/key_ma/en/3.9 

Although some pages only have a couple of lines on them, having the space to go into more detail (as with the linked) makes it a lot clearer. Having hyperlinks directly to the "reference" of how that button works wherever it's listed seems like it would be super helpful.

To be clear, I'm suggesting these links would be added automatically as part of the rendering process, not that they'd be added manually!!

**Comment by congoblue** [comment]
OK I see what you were thinking. I was just going to do a table with a couple of lines explanation a bit like the glossary, and I will probably start off like that to get the job started, but I can see that listing all the use cases of the button is useful.

I don't think that we should have explanations of how to do things in that button reference section though, I think that belongs in the main part of the manual - but it should make finding the right place in the manual a lot easier which is often difficult at the moment.

**Comment by Farrser** [comment]
Maybe we could use headings rather than a table so that each of the buttons can be linked to?

**Comment by congoblue** [comment]
Yes will do, will use the level 3 headings

**Comment by congoblue** [comment]
Fixed by PR #335
