### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by marcheimendinger** [AvolitesLtd/TitanManual#329]
It's a detail but… what about a dark mode on the website? And linked to the current operating system appearance.

See here: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by p--b** [comment]
Docusaurus 2 has support for this by stock:
https://v2.docusaurus.io/docs/api/themes/configuration/

I imagine when we move to Docusaurus 2, we will get this for free

**Comment by Farrser** [comment]
We now have dark mode
