### ISSUE TITLE
External Capture "Snapshot" keyboard button

### ISSUE THREAD

**Issue by Farrser** [AvolitesLtd/TitanManual#332]
**Link to the page in the manual:**
http://manual.avolites.com/docs/en/capture-visualiser/linking-the-console-to-stand-alone-capture/

**Old Text (if applicable):**
N/A

**New Text:**
You can legend playbacks/palettes etc from external capture using the CITP link. Set a picture legend as normal and change to the "network" tab in the keyboard. Any network legends, including a snapshot from the Capture Alpha view will show up allowing you to set it as a legend.

**Why it should be changed:**
This feature was news to me, probably news to a lot of people!

**Comment by congoblue** [comment]
I am trying to set this up to get screen shots - should it work with Capture 2018? Titan can't see CITP from Capture.

Also is it possible to set legends from the internal Capture window - I feel like I have seen examples of this somewhere.
