### ISSUE TITLE
Document `ArtPollDisabled` registry key

### ISSUE THREAD

**Issue by p--b** [AvolitesLtd/TitanManual#333]
**Link to the page in the manual:**
https://manual.avolites.com/docs/en/system-settings/dmx-output-mapping/#art-net-properties

**New Text:**
It's pretty niche, but we should document that you can disable ArtPoll messages from ever being sent by the Art-Net module by setting the registry key `HKEY_LOCAL_MACHINE\Software\Avolites\Titan\ArtPollDisabled` to `1`.

**Why it should be changed:**
It is non-obvious user configurable functionality that is not currently documented.

**Other Information:**
It is a registry key so that if you have fixtures that crash when they receive an ArtPoll message (!), Titan will *never* attempt to broadcast this message, irrespective of loaded show / configuration / etc.

**Comment by p--b** [comment]
(See also TFS#87733 RE this functionality)

**Comment by congoblue** [comment]
I feel this is a bit specialised to go in the manual - manually editing the registry is not really what I would call user-configurable, And there are obvious dangers with instructing users to edit the registry which would require quite a large section about how to use regedit and making backups etc. for those users who aren't experienced in poking around in the registry.

We could put a note that this is possible and to contact Avo support for instructions?

**Comment by p--b** [comment]
Part of my concern is that if you came across a console where this had been done, there's currently no documented way for users to know how to get it working again...

I know what you mean about the dangers of editing the registry, but I'd have thought just a sidebar that says

> This is a specialist procedure. Only proceed if you understand the risks of editing the registry and how to perform appropriate backups.

Would be enough?

**Comment by Farrser** [comment]
Do tend to agree that we shouldn't be telling people to edit the registry key. Really, I would say this functionality doesn't "exist" to the user until TFS#87733 is done (to make the option be exposed in the software).

Given that this code does exist though, maybe the best thing to do would be to include a note of some sort.

"The ArtPoll messages can be disabled via a registry setting. If ArtPoll messages aren't being sent, contact Avolites support for instructions on how to reset this."

That way, for people that know what they're doing, they can probably find the registry setting if they really want to. For everyone else, they should contact support if it's not working.

What do you guys think?

**Comment by congoblue** [comment]
I think a note like that would be the best thing. I really don't think registry edits should be included in the manual.

**Comment by p--b** [comment]
This seems reasonable
