### ISSUE TITLE
Masters transparent lock

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#334]
**Link to the page in the manual:**
https://manual.avolites.com/docs/en/running-the-show/playback-controls/#grand-master-fader-and-assignable-masters

**Old Text (if applicable):**
By default, master faders are set to have a transparent lock, which makes the master fader remain in position even when the playback page is changed. If you don't want this to happen you can change it by pressing OPTIONS (or Options softkey from the root menu) then press the Swop/Select button of the master.

**New Text:**
N/A

**Why it should be changed:**
Masters do not default to transparent lock . 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
This used to be true, what version did it change?

**Comment by KadeBehm** [comment]
Tested: 
Sim 9.1 10.1 
Quartz 11.4,12,12.1,13.0,14.0
Sapphire 14.0 

Didn't default to transparent lock  on any of the above

**Comment by congoblue** [comment]
Wow that's dedicated testing!
I have some old shows here where masters are set to transparent lock and I was confused as I am sure I did not set them manually.
Anyway the non-lock behaviour seems to go back quite a long way so I will update the manual to change that default and say instead how you would set a transparent lock.

**Comment by KadeBehm** [comment]
That seems like a good plan ! transparent lock is a handy tool for a master for sure.
