### ISSUE TITLE
Misleading wording re broadcast addresses

### ISSUE THREAD

**Issue by custardclark** [AvolitesLtd/TitanManual#340]
**Link to the page in the manual:**
https://manual.avolites.com/docs/en/networking/a-quick-guide-to-ip-addressing/?fbclid=IwAR3lVU4sdpvshbcSicGWO9pE1TH_aa47I4RQ5YUxVt_HVp7BjhKfiVNlzog

**Old Text (if applicable):**
The section of text that is currently incorrect or should be improved
Never set the last number of an IP address to be 255. This is a special address which will not function correctly.

**New Text:**
Delete or add a paragraph explaining subnets properly

**Why it should be changed:**
Describe why the change should be made, is the current description wrong? Does the software actually do something else? Is the way it's written confusing?

factually incorrect

**Other Information:**

The statement made is only true for a 255.255.255.0 subnet. In all other cases an IP address ending in 255 can be a valid non broadcast address.  Given that the documentation suggests using class A subnets in some cases this is misleading.  For example 10.1.1.255 /8 is a perfect;y acceptable host address, it is only 10.255.255.255 that is the broadcast address. 

I will contact Steve Warren to offer up some further assistance/wording

**Comment by congoblue** [comment]
Thanks for the pointers, this section has a number of problems - it's quite old, dating from when Art Net was first introduced. 

I think the "IP addressing" section could be combined with the "Setting the console's IP address" section since a lot of the information is repeated,

There should also be a link to the PioneerDJ setup section.

**Comment by congoblue** [comment]
Does this explain it correctly

> If the unmasked part of an IP address is set to 255, this acts as a broadcast address (for example `192.168.1.255` would be a broadcast address if the mask is `255.255.255.0`, or `10.255.255.255` if the mask is `255.0.0.0`). So it is best to avoid using 255 in the IP address.

**Comment by custardclark** [comment]
kind of but misleadingly so. Look at the example of 10.100.255.255 which with a subnet mask of 255.0.0.0 is a perfectly valid usable address. Better to give the full  understanding than rules with exceptions that mislead. You can mail me at stevec@productionscience.com for direct access. Or give me a number I can reach you on to discuss if easier? 
   
  
  
   
    On 26/02/2021 09:09 Tim Mitchell <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   Does this explain it correctly
   
    If the unmasked part of an IP address is set to 255, this acts as a broadcast address (for example 192.168.1.255 would be a broadcast address if the mask is 255.255.255.0, or 10.255.255.255 if the mask is 255.0.0.0). So it is best to avoid using 255 in the IP address.

**Comment by Farrser** [comment]
A simplistic explanation is good for a lot of our users. I think we have to realise that some people using the consoles might not understand binary, you don't even have to set dip switches on most fixtures now!

That said, we also shouldn't mislead/confuse people. I do agree that a simple worked example is probably the way to go as it will work for the vast majority of our users use cases. For anyone needing anything more complex then our manual probably isn't the source they should use to learn it.

Maybe we could signpost to a more authoritative source for a more comprehensive explanation?
