### ISSUE TITLE
Prism Manual shows who the page was last updated by where that information was chosen to be dropped in titan

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#367]
**Describe the bug**
Prism Manual shows who the page was last updated by where that information was chosen to be dropped in titan. It does not seem to me like this inconsistency should exist. When the manual was reviewed it was agreed we wouldn't show this.

**To Reproduce**
1. Open the manual
2. Go to Prism (Player or Zero)
3. Look at the bottom of the page.
Shows who it was last updated by. It should not.

**Screenshots**
![image](https://user-images.githubusercontent.com/29404400/130827045-b00f2d6f-b09d-40f6-90b8-e5899e038eb2.png)
![image](https://user-images.githubusercontent.com/29404400/130827084-8f30c733-61f6-4cfc-9084-e5d7fd310ec0.png)

**Desktop (please complete the following information):**
Manual version 1.0.0.8 on windows 10

**Comment by Farrser** [comment]
This has now been removed
