### ISSUE TITLE
Diamond 9 - Rear light (Red) can be turned on and off by holding down the front reading light switch for 2-5 seconds

### ISSUE THREAD

**Issue by KullyTheDonny** [AvolitesLtd/TitanManual#370]
This currently doesn't exist in the manual. 

The rear backlight (red) behind the screens can be turned on and off using the front reading light switch. This needs to be held for 2-5 seconds.

**Comment by congoblue** [comment]
is this different to the lighting around the connector panel?
Also where is the front reading light switch located as this isn't described either

**Comment by Farrser** [comment]
Yes this is different. There is a button on the front under the armrest towards the left side of the console. Pressing this button toggles the "headlight"/reading light. Holding for 5 seconds toggles the red backlight
