### ISSUE TITLE
Windows setup for Titan Go devices

### ISSUE THREAD

**Issue by marcheimendinger** [AvolitesLtd/TitanManual#388]
**Link to the page in the manual:**
https://manual.avolites.com/docs/about-the-consoles/t1-and-t2

Add a mention about disabling Windows USB Power Saving feature to avoid T1/T2/TM disconnection issues.

It could even be worth creating a brand new page with a list of things to do in Windows to setup a proper working station, similar to what QLab is doing with the Mac: https://qlab.app/docs/v4/general/preparing-your-mac/

**Comment by Farrser** [comment]
This seems like a really good idea. Just thinking of some other things that might be worth people doing:

- Turning off screensaver / sleep / auto lock
- Disable automatic windows updates
- Disable disk indexing
- Disabling windows firewall if you want to do networking things

**Comment by congoblue** [comment]
How much detail should we go into? Do we need to show how to do this in Windows (various versions of...) or is it just a list of things to check.

**Comment by Farrser** [comment]
I feel like if we include a screenshot of the switches in Windows 10 and a sentence on where to find it that would be enough

**Comment by marcheimendinger** [comment]
Just had an idea.... I don't really know as I'm more of a Mac person but maybe it's possible to change settings using the command line like on macOS? So the user can easily copy-paste commands to apply these changes. Or even better, a bash script which would apply all of these in a single command.
