### ISSUE TITLE
New AI images

### ISSUE THREAD

**Issue by Wrekriem** [AvolitesLtd/TitanManual#399]
Replace images in Synergy section of manual with up to date ones.

https://manual.avolites.com/docs/synergy

Replacement images:

[Uploaded to sharepoint](https://avoliteslimited-my.sharepoint.com/:f:/g/personal/gareth_weaver_avolites_com/EiC6qNrTCrhDi60TUkcLhuYBcke_zzPJ4wGyxWJeCf6JQg?e=Zruhu8)

**Comment by Wrekriem** [comment]
Cleared by Arran and Kully.

**Comment by congoblue** [comment]
These images are quite fuzzy due to jpg encoding, do you have as png?
Will use them as-is if not.

**Comment by Wrekriem** [comment]
When saving them I tested both png and jpg side by side and I saw no difference in quality. The synergy multi-view pictures are already png and aren't any sharper. Unfortunately I only saved images that are jpgs as such. Probably shouldn't have used paint...

**Comment by congoblue** [comment]
OK not to worry will use them like they are.

**Comment by Wrekriem** [comment]
Any luck with this? This was recently mentioned in a UX meeting and I noticed this is still open. Thanks!

**Comment by congoblue** [comment]
This is still on my list of things to be updated. Hopefully will get time in the next week or so.

**Comment by Wrekriem** [comment]
Any eta on this?

**Comment by congoblue** [comment]
I have updated this now, it is waiting for review of the changes, sorry for the delay.
Note, I have left the old images there as they are referenced by the previous versions.
