### ISSUE TITLE
The Tiger Touch wing section of the manual does not list the correct consoles or the main features of the wing.

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#406]
https://manual.avolites.com/docs/about-the-consoles/fader-wings#tiger-touch-wing

The Tiger Touch wing works with the D9. If you have a 3 screen console the left hand faders and the Tiger touch wing are the same handle group.

The Tiger Touch wing has a switch on the back to put it in the left or right position. This means you can attach 2 to a console. The switch position is only evaluated on start up.

**Comment by congoblue** [comment]
"the left hand faders and the Tiger touch wing are the same handle group" does this mean that the faders are duplicates of each other?
