### ISSUE TITLE
Change videos to be an icon instead of full size iframe

### ISSUE THREAD

**Issue by Farrser** [AvolitesLtd/TitanManual#42]
It would be good if videos could display as some sort of icon/button rather than full-size videos.

This would avoid bloat in the length of the page but still have the videos accessible to those that want to learn via video.

Clicking the video should expand downwards to show the video while maintaining the ability to scroll down the docs to read along while the video is playing.

Clicking the video icon should not navigate you away from the page.

https://fontawesome.com/icons/video?style=solid

**Comment by garethnunns** [comment]
Added in 3518d47f73064fc28d6e44ee5028c09e342e12eb
