### ISSUE TITLE
Document the different 'palettes in a playback’ functionality

### ISSUE THREAD

**Issue by Wrekriem** [AvolitesLtd/TitanManual#451]
https://manual.avolites.com/docs/palettes/using-palettes?_highlight=%22quick&_highlight=palettes#setting-palettes-to-all-fixtures-in-a-playback

**Old Text (if applicable):**
Setting Palettes to All Fixtures in a Playback
You can apply a palette to all fixtures in a particular playback. Hold the palette button and press the Select button of the playback which the palette is to apply to.

**New Text:**
Setting Palettes to All Fixtures in a Playback
You can apply a palette to all fixtures in a particular playback. Hold down a recorded palette and press the blue key (Top Key on the T3 or D9)

You can also hold down the grey key (Bottom Key on the T3 or D9) and tap a recorded palette.

Further details in this Avolites Academy video.

https://www.youtube.com/watch?v=_bmk7JEPpQo

**Comment by congoblue** [comment]
Hi, we decided that we would not use "Grey" and "Blue" keys any more in the manual as it required too much text to explain about D9 buttons each time.

Does that decision still stand?

--
Tim Mitchell
Sabre Technology (Hull) Ltd,
Lakeside House, Woodmansey Business Park,
Plaxton Bridge Road, Beverley, HU17 0RT
01482 241981 · www.sabretechnology.co.uk
________________________________
From: Wrekriem ***@***.***>
Sent: 22 May 2023 11:16
To: AvolitesLtd/TitanManual ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AvolitesLtd/TitanManual] Document the different 'palettes in a playback’ functionality (Issue #451)


https://manual.avolites.com/docs/palettes/using-palettes?_highlight=%22quick&_highlight=palettes#setting-palettes-to-all-fixtures-in-a-playback

Old Text (if applicable):
Setting Palettes to All Fixtures in a Playback
You can apply a palette to all fixtures in a particular playback. Hold the palette button and press the Select button of the playback which the palette is to apply to.

New Text:
Setting Palettes to All Fixtures in a Playback
You can apply a palette to all fixtures in a particular playback. Hold down a recorded palette and press the blue key (Top Key on the T3 or D9)

You can also hold down the grey key (Bottom Key on the T3 or D9) and tap a recorded palette.

Further details in this Avolites Academy video.

https://www.youtube.com/watch?v=_bmk7JEPpQo

**Comment by Wrekriem** [comment]
Probably best to stick to whatever convention you agreed and have been using. I don't expect what I wrote to be used verbatim.
