### ISSUE TITLE
Correct what the manual says about Clear located attributes

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#498]
https://manual.avolites.com/docs/controlling-fixtures#setting-fixtures-to-a-start-position-locate

Currently the manual is a little misleading. What it says:
Option Clear/Don't Clear Located Attributes sets whether the attributes changed by the Locate function will be saved into any cues you store. If the option is set to "Clear" then the Located attributes will not be stored in the Programmer unless you modify them using the wheels. This is useful if for example you want to program a cue which sets the position of fixtures, but does not turn them on. The Locate button will light up the fixtures for programming, but the lit state will not be stored in any cues you save.

What it should say:
Option Clear/Don't Clear Located Attributes sets whether the attributes changed by the Locate function will remain in the programmer. If the option is set to "Clear" then the Located attributes will be removed from the programmer on locate. The default is Don't Clear Located Attributes which means attributes are left in the programmer. If you switch this to "Clear Located Attributes" it will mean that you are less likely to store attributes at locate values when recording by channel.

**Comment by congoblue** [comment]
Can you explain this more, I don't understand how it works
"If the option is set to "Clear" then the Located attributes will be removed from the programmer on locate"
Should that say "removed from the programmer on Record"?

**Comment by PeterBuddAvo** [comment]
@congoblue this option only changes the behaviour of the console at the point someone presses the locate button. In this case attributes are removed from the programmer. Clearly what is in or isn't in the programmer will affect subsequent records.

For example:
1. Start a new show
2. Patch a fixture with Pan and Tilt.
3. Change the Pan and Tilt values
4. Press Locate - Attributes are still in the programmer as indicated by the highlighting on the wheels and IPCGBES.
5. Change the option to Clear Located Attributes
6. Change Pan and Tilt Values.
7. Press Locate.
Observe that Pan and Tilt are no longer in the programmer.

**Comment by congoblue** [comment]
Thanks, I had misunderstood this option.
I tested this, when set to "Don't Clear" then attributes already in the programmer are changed on locate (so the pan tilt goes to 50/50 in the programmer). Is the use case for this to avoid accidentally storing located values when using record by channel?

**Comment by PeterBuddAvo** [comment]
That is the only use case I can think of. I think this feature has been in for years so it is possible it was originally added with some other thoughts.
