### ISSUE TITLE
Add download option to versions page

### ISSUE THREAD

**Issue by garethnunns** [AvolitesLtd/TitanManual#52]
Could add an option to the [versions page](https://manual.avolites.com/versions/) to download the PDF/electron app

**Comment by garethnunns** [comment]
We could use the GitHub API for this, e.g. https://api.github.com/repos/garethnunns/AvoDocs/releases/latest

Or alternatively in the GitHub action we transfer all the generated downloads to the server then have an API on the server? Need a way of listing the files in the downloads folder of the server - it would be nice not to use PHP since the rest of the project is Node... can we run node on the server? Or we could have the action produce a JSON file...

**Comment by Farrser** [comment]
It looks like the files are fairly static after they've been created so we could do it in react and then it would be static after generation maybe?

https://github.com/AvolitesLtd/TitanManual/archive/1.0.5.zip

**Comment by garethnunns** [comment]
That would mean waiting for all of the apps to build and the PDF then generating the whole site... Could we make it generate symlinks on the server so manual.avolites.com/downloads/titan-v13.pdf points to the latest one produced?
