### ISSUE TITLE
Add a test that runs on PRs to make sure the builds passes

### ISSUE THREAD

**Issue by Farrser** [AvolitesLtd/TitanManual#72]
Add a test that runs on pull requests to make sure the builds pass including making sure all of the links are valid.

**Comment by garethnunns** [comment]
Would be a good chance to make a parse lib too

**Comment by garethnunns** [comment]
The test workflow currently just builds the site, we could also make it build the PDF but this will mean a lot more billed time

**Comment by Farrser** [comment]
I think we can call this done. Not too worried about testing the PDF every time, I think if that's being worked on we'll just have to make sure we run the build through to make sure it still works in the build system.
