### ISSUE TITLE
Trigger Actions

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#75]
**Link to the page in the manual:**
https://manual.avolites.com/docs/running-the-show/midi-dmx-or-audio-triggering//

**Old Text (if applicable):**
The section of text that is currently incorrect or should be improved

**New Text:**
Add a section explaining what each actions does, Example: 
Item Trigger Types have the following Actions:
Set Level - Sets the level (best with faders/knobs) 
Fire at Level - Like Set Level but ignores “Level Match” and will “kill at 0” automatically on a cuelist. (best with faders/knobs)
Re-Fire At Level - Will re fire LTP attributes if the level is changed any. (best with faders/knobs)
Flash - Flashes the playback (best with buttons) 
Swop - Swops the Playback (best with buttons) 
Preload - Preloads the playback , similar to Move In Dark on a cuelist (best with buttons) 
Latch - Latches the playback on (best with buttons)

**Why it should be changed:**
This has never been in the manual, and has never been clear ( multiple Avo staff haven't been able to explain them all )  

**Other Information:**
Any other information

**Comment by Farrser** [comment]
I do agree on this. People often get very confused at the moment.

I seem to see a lot of people tripped up by using Set Level rather than Re-Fire At Level but I'm not sure why set level doesn't work as expected for them?

**Comment by congoblue** [comment]
The latest v14 text now explains this in more detail but Kade's explanations are better than mine so will update.

**Comment by congoblue** [comment]
Action explanations added for next update.
