### ISSUE TITLE
Audio Triggers Bands

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#76]
**Link to the page in the manual:**
https://manual.avolites.com/docs/running-the-show/midi-dmx-or-audio-triggering/

**Old Text (if applicable):**
None

**New Text:**
List what Frequency each band is, From a tone gen I got these numbers as the center of each: 
Band 1: 50Hz
Band 2: 140Hz
Band 3: 380Hz
Band 4: 875Hz
Band 5: 2400Hz
Band 6: 6200Hz
Band 7:14000Hz

**Why it should be changed:**
Would help users understand how they work easier. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
Added this useful information for next update.
