### ISSUE TITLE
Audio Triggers additional-

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#77]
**Link to the page in the manual:**
https://manual.avolites.com/docs/running-the-show/midi-dmx-or-audio-triggering/

**Old Text (if applicable):**
On the Arena console, the Audio LED (just above the power switch) will flash when audio is received. Note that the headphone socket on the Arena is linked to the motherboard audio output and can't be used for monitoring the audio trigger input.

**New Text:**
On the Arena and Quartz consoles, the Audio LED (just above the power switch) will flash when audio is received. Note that the headphone socket on the Arena/Quartz is linked to the motherboard audio output and can't be used for monitoring the audio trigger input.

**Why it should be changed:**
Quartz also has this function. 

**Other Information:**
Any other information

**Comment by congoblue** [comment]
This has been updated for the next release.
