### ISSUE TITLE
Search for Find Fixture 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#78]
**Describe the bug**
when searching for "Find Fixture" the first 3 results return with 404 when clicked. 

**To Reproduce**
1. search for "Find Fixture" 
2. Click on Patching fixtures , Patching fixtures  view fixture patch, or Patching fixtures  Setting Fixture options
3. All 3 return a 404 error. 

**Expected behavior**
to not return a 404 error

**Desktop (please complete the following information):**
 - OS:Mac OS
 - Browser: Safari
 - Version 13.1.2

Addtionally Searching for find fixture should return the proper section which it does not .

**Comment by Farrser** [comment]
This is as a result of the search being populated from the @next version instead of the @current version (or better, using per version search).

The fix for this should change the search index to be per version and link to the correct versions in the results.

**Comment by Farrser** [comment]
This should now be fixed in [c14952d](https://github.com/AvolitesLtd/TitanManual/commit/c14952d14d7f6445281e0d4e9225a0c31fda3c00)
