### ISSUE TITLE
The manual incorrectly says that manual crossfade transitions to the next cue the end of the crossfade

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#82]
The only current mention of manual crossfade says:
The fader behaves as a manual crossfade control, and the cue list will automatically step on to the next cue when the fader reaches the top or bottom of travel.

First off this is now incorrect it steps onto the next cue when beginning the travel rather than ending it. I think some further explanation of manual crossfade might be helpful. Areas should include:
- That a fade can be captured midway with a fader. (82950)
- That when firing a cuelist in manual crossfade the intensity snaps to full
- Shapes and Pixel Maps fade in with the manual crossfade, but when you return to 0 they are not removed so may still affect the output. (84685, 80391)
- Autoloads fade with there time ignoring the fader completely. (84686)
- How linked cues work (86148)
- The option to disable linked cues (86213)

**Comment by p--b** [comment]
Potentially also that you can automatically complete a partially crossfaded cue with [Go]

**Comment by garethnunns** [comment]
Would here be the best place to put this: https://manual.avolites.com/docs/cue-lists/cue-list-options/#fader-mode

Would the following phrasing work:

### Cue List Fader Mode
Sets how the cue list fader behaves.

Setting | Action
--- | ---
Fader Mode Intensity Kill With Off | The fader masters the overall HTP level and the cue list remains active (connected) even when the fader is lowered to zero.
Fader Mode Intensity Kill At 0 | The fader masters the overall HTP level and the cue list is killed when the fader is lowered to zero.
Manual Crossfader | The fader behaves as a manual crossfade control, and the cue list will automatically step on to the next cue when the fader begins travel from top or bottom.

#### Notes on Manual Crossfader
- A fade can be captured midway with the fader
- When firing a cuelist in manual crossfade the intensity snaps to full
- [Shapes](https://manual.avolites.com/docs/effects/shape-generator/) and [Pixel Mapper](https://manual.avolites.com/docs/effects/pixel-mapper/) effects will fade in with the manual crossfade, but when the fader returns to 0 they are not removed so may still affect the output
- [Autoloads](https://manual.avolites.com/docs/cue-lists/creating-a-cue-list/#autoloading-a-playback-within-a-cue-list) fade times will use their specified times, regardless of the manual crossfade performed by the fader
- Partially completed crossfades can be completed using \[Go\]

**Comment by congoblue** [comment]
I think "A fade can be captured midway with the fader" needs more explanation - I am not sure what you mean

**Comment by congoblue** [comment]
Added gareth's text to cue-lists/cue-list-options.md
