### ISSUE TITLE
The manual should mention that the connected handle is per user

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#84]
The only mentions of the connected handle I can find show the layout of the connected area. 

It would be worth mentioning that all consoles in a session will share a connected cue list or chase. If this is undesired behaviour your other consoles require their own users. (86216)

**Comment by p--b** [comment]
To be nitpicky, all consoles in the same session having the same user *and* handle world will have the same connected handle. But yes, this should probably be mentioned

**Comment by garethnunns** [comment]
Would here be a good place to mention this: https://manual.avolites.com/docs/titan-basics/multi-user-operation/#handle-worlds

**Comment by p--b** [comment]
yes
