### ISSUE TITLE
The Power and UPS behaviour section of the manual should mention the new V14 features

### ISSUE THREAD

**Issue by PeterBuddAvo** [AvolitesLtd/TitanManual#85]
The Power and UPS behaviour of the manual is no longer quite complete. I think it would be worth mentioning the following:
- The UPS will now show a full screen warning on your console.
- Your show will be autosaved when the UPS kicks in
- If a console or TNP in your session is running off UPS an error will appear in the event log.

**Comment by congoblue** [comment]
Added information to /titan-basics.md in /feature/v14 version
