### ISSUE TITLE
Clarify separate copy and move functions

### ISSUE THREAD

**Issue by icke-siegen** [AvolitesLtd/TitanManual#95]
See /cues/copying-moving-linking-and-deleting.md. Starting with v14 <Copy> only toggles between Copy and Link while Move is only available with the <Move> button. The manual should better reflect this.

**Comment by congoblue** [comment]
Just to be clear, how do you get "Move" on consoles which do not have a <Move> button i.e. Tiger Touch mk1 and Pearl Expert?

**Comment by icke-siegen** [comment]
I believe on those old consoles it still works in the old way (cannot test this right now). However I believe in this case the manual should describe this separately:

- if you want to copy press <Copy>
- if you want to link press <Copy> twice
- if you want to move press <Move>. If your console doesn't feature a <Move> button press <Copy> three times

**Comment by garethnunns** [comment]
I think you can also press Avo + Copy to get to move

**Comment by congoblue** [comment]
I will rewrite this section to describe the "Copy" and "Move" functions separately. The current text is from the "old" consoles which just had one button for all 3 functions.

**Comment by icke-siegen** [comment]
I tried this with the simulator now.
- on an old Tiger Touch layout, multiple presses on <Copy> cycle through copy, link and move, and Gareth's shortcut directly jumps to move as indicated on the laminate
- on a Titan Mobile, multiple presses on <Copy> only toggle between copy and link. Avo+Copy doesn't do anything extra, and the only way to move is pressing the <Move> key.

**Comment by icke-siegen** [comment]
While combing through the manual again, there are various places where this needs to be corrected (e.g. copying/moving fixture, palettes, cues...). Don't know if or how this could be corrected.
