### ISSUE TITLE
Fixture Overlap described in various places

### ISSUE THREAD

**Issue by icke-siegen** [AvolitesLtd/TitanManual#96]
Fixture Overlap is described in some places, in varying detail:
- https://manual.avolites.com/docs/next/cues/cue-timing/#setting-fade-times-and-overlap-for-a-cue
- https://manual.avolites.com/docs/next/cues/playback-options/#fixture-overlap

Additionally you find this for cuelists, chasers, palettes.

Maybe this could be streamlined a little more: one thorough explanation, and all the other parts linking there.

**Comment by garethnunns** [comment]
I've had a go at this with c77f010, have a look and let me know what you think

**Comment by congoblue** [comment]
While I think it is a good idea to link to a single section on this, I think some information is lost by this edit. Particularly Attribute Overlap which was explained (for some reason) only in the diagram in the Chase chapter and is not mentioned in the Cue chapter which now remains.

Is it OK if I edit your branch to add this back in?

**Comment by garethnunns** [comment]
Yeah go for it, didn't mean to lose info
